### ISSUE TITLE
FizzBuzz

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#108]
Write a program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”.

**Comment by RazvanBugoi** [comment]
```(javascript)
function prints(a) {
  if (a <= 100 && a % 3 === 0 && a % 5 === 0) {
      return "FizzBuzz";
  } else if (a <= 100 && a % 3 === 0) {
      return "Fizz";
  } else if (a <= 100 && a % 5 === 0) {
      return "Buzz";
  }
}
```

Is this ok?

**Comment by odv** [comment]
@RazvanBugoi  You are extremely close as you got part of it right. This program needs to output all numbers from 1 to 100(inclusive) so a function is not needed anymore. For multiples of three, console.log the string'Fizz' instead of the number and for multiples of five console.log the string 'Buzz'. For numbers that are multiple of both three and five, console.log 'FizzBuzz'. 

If some of the numbers fail this test, just output them to the console.

Here is a part of what I should get as output when running your loop:
```(javascript)
/*
1  
2  
Fizz  
4  
Buzz  
Fizz  
7  
8  
Fizz  
Buzz  
11  
Fizz  
...
*/
```

**Comment by RazvanBugoi** [comment]
```(javascript)
for (let i=1; i <= 100; i++) {

  if (i % 3 === 0 && i % 5 === 0) {
      console.log("FizzBuzz");
  } else if (i % 3 === 0) {
      console.log("Fizz");
  } else if (i % 5 === 0) {
      console.log("Buzz");
  } else {
      console.log(i);
  }
}
```

Now?

**Comment by odv** [comment]
@RazvanBugoi  Well done!
