### ISSUE TITLE
Why isn't this function executing correctly?

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#14]
```(javascript)
function multiply(a, b) {
  a * b;
}
```

**Comment by RazvanBugoi** [comment]
It is not executing correctly because it is incomplete. 

It should look like this: 
```javascript
function multiply(a, b) {
  return a * b;
}

let result = multiply(7, 7);
alert(result);
``` 

We need a return - to tell function to give us a return;
We need a variable to store the value in.
We need parameters to execute the function.

**Comment by odv** [comment]
@RazvanBugoi  Well done!
