### ISSUE TITLE
Write a function that accepts one *string* parameter and converts it to a number

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#15]
Function name should be **stringToNumber**
Note: All input served to this function will be valid so you don't need to test for invalid input. All strings will be representations of numbers.
Examples of running the function with different inputs:

```(javascript)
stringToNumber("1234") == 1234
stringToNumber("605" ) == 605
stringToNumber("1405") == 1405
stringToNumber("-7"  ) == -7
```

**Comment by RazvanBugoi** [comment]
Here is an example : 

```javascript
function stringToNumber() {
  alert("-343");
}

stringToNumber();
```

**Comment by odv** [comment]
@RazvanBugoi Your function doesn't have any parameter or return statement. Look closely at the examples I gave you above. On the left of the '==' operator is my input and on the right of the '==' is what I should get as output. 

When giving different inputs(like the ones from the examples) to your function, I still get the same output. That shouldn't happen.

**Comment by RazvanBugoi** [comment]
Like this ? 

```javascript
function stringToNumber(a, b) {
  return 55 + 43;
}

let result = stringToNumber();
alert(result);
```
