### ISSUE TITLE
Write a function that accepts a **boolean** paramenter and returns the opposite of it

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#16]
Note: Function will only receive valid inputs so no need to test for invalid cases now. Find a descriptive name for it.
Output: Function should output the opposite boolean. If I pass it true, it should return false(boolean).

**Comment by RazvanBugoi** [comment]
```(javascript)
function oppositeBoolean(a) {
    if ( a == 'true' ) {
        return 'False';
    }
    if ( a == 'false' ) {
        return 'True';
    }
}
```

**Comment by odv** [comment]
@RazvanBugoi  Check the exercise again and then your function body. Also run your code on jsbin or in the Chrome console.

**Comment by RazvanBugoi** [comment]
function oppositeBoolean(a) {
    if ( a == true ) {
        return 'False';
    }
    if ( a == false ) {
        return 'True';
    }
}
