### ISSUE TITLE
Solve 'Color Ghost'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#206]
https://www.codewars.com/kata/color-ghost/train/javascript

**Comment by RazvanBugoi** [comment]
@odv I don't understand how to make this.color display more results since I can only give it one attribute. It's a constructor so I can only use once this.color and assign a value to it, but the exercise says to return 4 values. How do I do that? 

```(javascript)
var Ghost = function() {
  this.color = "white";
};
```

**Comment by RazvanBugoi** [comment]
```(javascript)
var Ghost = function() {
  let colors = ["white", "yellow", "purple", "red"];
  this.color = colors[Math.floor(Math.random() * colors.length)];
};
```
