### ISSUE TITLE
Solve 'Hello World - Without Strings' 🔥 

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#221]
https://www.codewars.com/kata/hello-world-without-strings/train/javascript

**Comment by RazvanBugoi** [comment]
@odv  Can you check if the tests are OK please? It seems to me like I've done everything right.

```(javascript)
const helloWorld = () => {
  return String.fromCharCode(72, 101, 108, 108, 111, 44, 160, 87, 111, 114, 108, 100, 33);  
};
```
