### ISSUE TITLE
Solve 'Not so black box' 🔥 

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#222]
https://www.codewars.com/kata/not-so-black-box/train/javascript

@RazvanBugoi  This is a more challenging kata. Think about all the concepts we've learned so far and in particular think about a constant observation I've been making in your code. That keyword together with another already built-in function can help you solve this quite easily.

**Comment by RazvanBugoi** [comment]
@odv  I can't figure out how to solve this one yet...

**Comment by RazvanBugoi** [comment]
```(javascript)
JSopenSesame();
```
