### ISSUE TITLE
Solve 'Unique numbers'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#228]
https://www.codewars.com/kata/unique-numbers/train/javascript

**Comment by RazvanBugoi** [comment]
@odv I have got to this point and now it returns this  " Expected: '[1, 2, 3, 5, 6]', instead got: '[Set { 1, 2, 3, 5, 6 }, Set { 1, 2, 3, 5, 6 }, Set { 1, 2, 3, 5, 6 }, Set { 1, 2, 3, 5, 6 }, Set { 1, 2, 3, 5, 6 }, Set { 1, 2, 3, 5, 6 }, Set { 1, 2, 3, 5, 6 }, Set { 1, 2, 3, 5, 6 }, Set { 1, 2, 3, 5, 6 }, Set { 1, 2, 3, 5, 6 }]' " 

What to do now? 

```(javascript)
function uniqueNumbers(numbersArray) {
    let set = new Set();
    let output = numbersArray.map(item => (set.add(item)));
    return output;
}
```

**Comment by odv** [comment]
@RazvanBugoi  You now need to convert your output to a different type before returning it.

**Comment by RazvanBugoi** [comment]
```(javascript)
function uniqueNumbers(numbersArray) {
    let set = new Set(numbersArray);
    return Array.from(set);
}
```
