### ISSUE TITLE
Solve 'Training JS #18: Methods of String object--concat() split() and its good friend join()'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#242]
https://www.codewars.com/kata/training-js-number-18-methods-of-string-object-concat-split-and-its-good-friend-join/train/javascript

**Comment by RazvanBugoi** [comment]
@odv I'm stuck on this one too. Any tips?

```(javascript)
function splitAndMerge(str,sp){
  let words = str.split(" ");
  return words.join(" ").split("").join(sp);
}
```

**Comment by odv** [comment]
@RazvanBugoi Test it in your console. You are on the right track but you just have logic issues. Pick an input from your sample tests and try running your existing code with that input.

**Comment by RazvanBugoi** [comment]
```(javascript)
function splitAndMerge(str,sp){
 let words = str;
 return words.split(" ").map(index => index.split("").join(sp)).join(" ");
}
```
