### ISSUE TITLE
Solve 'Initialize my name'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#244]
https://www.codewars.com/kata/initialize-my-name/train/javascript

**Comment by RazvanBugoi** [comment]
@odv  I'm stuck on this one. I figured how to select first and last name but I don't know how to do the rest. How to select the in between indexes and modify them to meet the criteria.

```(javascript)
function initializeNames(name){
let input = name; 
let arr = input.split(" ");
let first = arr.shift();
let last = arr.pop();
let firstAndLast = first + " " + last;
}
```

**Comment by odv** [comment]
@RazvanBugoi You are not specific in your case and assume that you will always get the same sort of input.

Test for cases listed in the Example section. You already have the syntax, just need to work on your logic.

**Comment by RazvanBugoi** [comment]
```(javascript)
function initializeNames(name){
  let input = name; 
  let output = "";
  let arr = name.split(" ");
  if (arr.length > 2) {
  output += arr[0] + " ";
  for (let i=1; i < arr.length - 1; i+=1) {
  output += arr[i][0] + "." + " ";
  }
  output += arr[arr.length - 1];
  return output;
  } else {
  return input;
  }
}
```
