### ISSUE TITLE
Solve 'Array.prototype.size()'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#256]
https://www.codewars.com/kata/array-dot-prototype-dot-size/train/javascript

**Comment by RazvanBugoi** [comment]
@odv I don't understand, am I not supposed to use .length at all ?
```(javascript)
Array.prototype.size = function() {
  return this.length;
};
```

**Comment by odv** [comment]
@RazvanBugoi You are on the right track but read the instructions again. 'But do it entirely without using Array.prototype.length!' 

You should not use .length at all.

**Comment by RazvanBugoi** [comment]
```(javascript)
Array.prototype.size = function() {
  let length =0; 
  this.map(index => length += 1);
  return length;
};
```
