### ISSUE TITLE
Question 1

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#259]
We perform the following list of actions: 

1.  Insert the following elements into a set: 1,2,9,1,2,3,1,4,1,5,7

2.  Convert the set into a list and sort it in ascending order

Select an option below that denotes the sorted list:

1. {1, 2, 3, 4, 5, 7, 9}
2. {9, 7 , 5, 4, 3, 2, 1}
3. {1. 1. 1. 1. 2. 2.  3, 4, 5, 7, 9}
4. None of the above

**Comment by RazvanBugoi** [comment]
```(javascript)
const numbers = [1, 2, 9, 1, 2, 3, 1, 4, 1, 5, 7];

const set = new Set(numbers);

const arrayFromSet = Array.from(set);

console.log(arrayFromSet.sort()); 
// output : [1, 2, 3, 4, 5, 7, 9]
```

So the right answer is 4.
