### ISSUE TITLE
Solve 'Configure package json for a node application'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#266]
You can take a look at how to create a package.json file here: https://docs.npmjs.com/creating-a-package-json-file#example-1

The only thing I want here is for you to practice using JSON and distinguish it from regular JS objects.

https://www.codewars.com/kata/configure-package-json-for-a-node-application/train/javascript

**Comment by RazvanBugoi** [comment]
```(javascript)
const configuration = {
  "name": "firstpackage",
  "version": "1.0.0",
  "description": "sad",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
};
```
