### ISSUE TITLE
Simple Fun #1: Seats in Theater

### ISSUE THREAD

**Issue by RazvanBugoi** [js-mentorship/javascript#336]
https://www.codewars.com/kata/simple-fun-number-1-seats-in-theater/train/javascript

**Comment by RazvanBugoi** [comment]
```(javascript)
function seatsInTheater(nCols, nRows, col, row) {
let colsBehind = nCols - col + 1;
let rowsBehind = nRows - row;
return colsBehind * rowsBehind;
}
```

**Comment by jakezg0** [comment]
Solution in Dart:
var colsBehind = nCols - col + 1;
var rowsBehind = nRows - row;
return colsBehind * rowsBehind;
