### ISSUE TITLE
Write a function which detects unique and repeated numbers.

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#399]
Write a function which accepts an array and returns back numbers which are unique and which are repeated.

[3,4,5,6,9,10,3,4,2,9,4,3,9,3]

Example output should be as follows:

Unique numbers : 5,6,10,2
Repeat numbers : 3 (4 times), 4 (3 times), 9 (2 times)

**Comment by RazvanBugoi** [comment]
```
let listOfNumbers = {};
const input = [3,4,5,6,9,10,3,4,2,9,4,3,9,3];
let unique = [];
let repeated = []; 
input.map((element) => element in listOfNumbers ? listOfNumbers[element] += 1 : listOfNumbers[element] += 0);
```

**Comment by odv** [comment]
@RazvanBugoi  You should increase the count if the element is not there or add an initial value if it's the **first** time the element is seen. You are getting NaN because you are not doing something correctly.

**Comment by RazvanBugoi** [comment]
```
input.map((element) => element in listOfNumbers ? listOfNumbers[element] += 1 : listOfNumbers[element] = 1);
for ( let key in listOfNumbers ) {
    listOfNumbers[key] == 1 ? unique.push(key) : repeated.push(key);
}
unique.join();
repeated.map((element) => element + ` (${listOfNumbers[element]} times)`).join(', ');
```
