### ISSUE TITLE
Write the differences between dot notation and bracket notation in objects

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#402]
Come up with actual code examples.

**Comment by RazvanBugoi** [comment]
The dot notation can't access multi-word properties, properties that start with a digit and properties that include special characters ( $ and _ are allowed).  So, when properties names are known and simple, we should use dot notation. If we need something more complex, we can then switch to using square brackets. 

Examples: 

```(javascript)
let kid = {
   age: '9',
   name: 'Albert',
   "hair color": 'black',
};

kid.age // output: 9
kid.name // output: 'Albert'
kid.hair color // would give a syntax Error because JS engine thinks we are trying to access kid.hair property which doesn't exist.
``` 

To be able to fix access the last property, we have to use bracket notation and it will look like this: 
```(javascript)
kid['hair color'] // output: 'black'
```
Now it works as expected.

**Comment by odv** [comment]
Dot notation doesn't allow you to use variables while square bracket notation does.

```
let kid = {
   age: '9',
   name: 'Albert',
   "hair color": 'black',
};
```

```
let property = 'age'
undefined
kid.property 
undefined
kid[property]
"9"
```
