### ISSUE TITLE
Number of People in the Bus

### ISSUE THREAD

**Issue by RazvanBugoi** [js-mentorship/javascript#430]
https://www.codewars.com/kata/5648b12ce68d9daa6b000099/train/javascript

**Comment by RazvanBugoi** [comment]
```
let number = function(busStops){
  let peopleIn = 0;
  let peopleOut = 0;
    for (let i=0; i<busStops.length; i++) {
      peopleIn += busStops[i][0];
      peopleOut += busStops[i][1];
  }
  return peopleIn - peopleOut;
}
```

**Comment by MondoBurrito** [comment]
> ```
> let number = function(busStops){
>   let peopleIn = 0;
>   let peopleOut = 0;
>     for (let i=0; i<busStops.length; i++) {
>       peopleIn += busStops[i][0];
>       peopleOut += busStops[i][1];
>   }
>   return peopleIn - peopleOut;
> }
> ```

Great solution. I suggest you space our your for let loop, curly brackets, and various code blocks to make it easier to read.

> ```
> let number = function(busStops) {
>
>   let peopleIn = 0;
>   let peopleOut = 0;
>
>   for (let i = 0; i < busStops.length; i++) {
>       peopleIn += busStops[i][0];
>       peopleOut += busStops[i][1];
>   }
>
>   return peopleIn - peopleOut;
> }
> ```

**Comment by kavak9494** [comment]
hello, why we write **[1]** in -  peopleOut += busStops[i][1]; why not other simbol???
i dont understand it
and why we write **[0]** in -  peopleIn += busStops[i][0]; why not other simbol???
i dont understand it too
