### ISSUE TITLE
DOM select and click

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#479]
<img width="885" alt="Screenshot 2020-04-20 at 18 39 53" src="https://user-images.githubusercontent.com/5067625/79770631-58d44380-8336-11ea-9229-90ebe52726f2.png">

Extract the 'Google Search' button from the DOM, store it in a variable then call a method on it so that when this action will be performed, Google will display the relevant search results.

**Comment by RazvanBugoi** [comment]
```
let button = document.getElementsByClassName('gNO89b');
button[1].click()
```
