### ISSUE TITLE
What is wrong in this example?

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#5]
Don't focus on forEach as we haven't discussed it yet.  Both alert and forEach are written correctly yet the code will produce an error. Why?

```(javascript)
alert("There will be an error after this message")

[1, 2].forEach(alert)
```

**Comment by RazvanBugoi** [comment]
I've tested both codes individually they work properly, no errors encountered.

**Comment by odv** [comment]
@RazvanBugoi You shouldn't test individually. As I said, both alert and forEach are written correctly but when you execute the whole code above you get an error. 

Why?

**Comment by RazvanBugoi** [comment]
First line of code is missing semicolon.
