### ISSUE TITLE
Solve 'Sum Mixed Array'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#66]
https://www.codewars.com/kata/sum-mixed-array/train/javascript

Remember that you have different types of values in your array: strings and numbers. You need to convert each item of the array before adding it in order to find out the sum.

**Comment by RazvanBugoi** [comment]
```(javascript)
function sumMix(x){
return x.reduce((sum, current) => Number(sum) + Number(current), 0);
}
```
