### ISSUE TITLE
Solve 'Push a hash/an object into array'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#74]
https://www.codewars.com/kata/push-a-hash-slash-an-object-into-array/discuss/javascript

@RazvanBugoi Sample tests are not working.

**Comment by RazvanBugoi** [comment]
```(javascript)
let items = [];
items.push({a: "b", c: "d"});
return items; 
```

How do I know if it's right or wrong without the tests? 
I've done it in JS Bin and it returns [object Object].
