### ISSUE TITLE
Solve 'Beginner - Lost Without a Map'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#78]
https://www.codewars.com/kata/beginner-lost-without-a-map/train/javascript

**Comment by RazvanBugoi** [comment]
```(javascript)
function maps(x){
const double = x.map(item => item * 2);
return double;
}
```

**Comment by odv** [comment]
@RazvanBugoi Well done! You can make this function even more succinct by not using a variable and just returning x.map directly.
