### ISSUE TITLE
Solve 'Find numbers which are divisible by given number'

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#80]
https://www.codewars.com/kata/find-numbers-which-are-divisible-by-given-number

**Comment by RazvanBugoi** [comment]
```(javascript)
function divisibleBy(numbers, divisor){
let divisible = numbers.filter(item => item % divisor == 0);
return divisible;
}
```

**Comment by odv** [comment]
@RazvanBugoi  Well done! As I said in a similar issue, you can make this function more succinct by removing the variable and just return numbers.filter directly.
