### ISSUE TITLE
How many times will this while loop be tested?

### ISSUE THREAD

**Issue by odv** [js-mentorship/javascript#9]
```(javascript)

let a = 3
while ( a >= -4 ) {
  a -= 2
}
```

**Comment by RazvanBugoi** [comment]
It will only be tested once and the result is -5

**Comment by odv** [comment]
@RazvanBugoi Look at the code more carefully. Replace a with the actual value(inside the condition) and tell me how many times is the loop **tested**. 

Also, tell me all the values that **a** will take until the condition is no longer true.

**Comment by RazvanBugoi** [comment]
First run will look like this : 
 3 > -4 and a = 3 - 2 = 1 ; 

Then a becomes 1 and we run loop again: 
1 > -4 and a = 1 - 2 = -1;

Now a becomes - 1 and we run loop again: 
-1 > -4 and a = -1 - 2 = -3; 

Then a becomes -3 and we run loop one more time:
-3 > -4 and a = -3-2 = -5.

-5 !>= -4 and so the loop will stop there. 

Final answer is: loop was tested 4 times.

**Comment by odv** [comment]
@RazvanBugoi You are extremely close to the answer. 

Hint: Check the last two statements that you wrote in your reply then read the question again.

**Comment by RazvanBugoi** [comment]
Yes, you are right, the correct answer is loop will be tested 5 times. He has to know when to stop so last run also counts.

**Comment by odv** [comment]
Well done!
